# Generated by Django 5.1.4 on 2024-12-07 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_paper_issue_rename_file_paper_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.journal'),
            preserve_default=False,
        ),
    ]
