# Generated by Django 5.1.4 on 2024-12-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_paper_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
